image: docker:latest

variables:
  DOCKER_DRIVER: overlay

stages:
  - test
  - build
  - image
  - deploy

web:test:
  image: node:13-alpine # specify version of node so that no node-version-related compatibility issues will occur later on
  stage: test
  script:
    - npm install
    - npm run test
  allow_failure: false

web:build:
  image: node:13-alpine
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - modules/web/build/

web:image:
  stage: image
  allow_failure: false
  services:
    - docker:dind
  dependencies:
    - web:build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE -f docker/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE
